name: '[Backend NestJs] checks'

on:
  push:
    paths:
      - backend-nestjs/**
    branches:
      - main
  pull_request:
    paths:
      - backend-nestjs/**
    branches:
      - main

defaults:
  run:
    working-directory: ./backend-nestjs

jobs:

  Checks:
    name: Install, build and lint
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint
