name: '[Frontend SvelteKit] deploy to Vercel'

on:
  push:
    paths:
      - frontend-sveltekit/**
    branches:
      - main
  pull_request:
    paths:
      - frontend-sveltekit/**
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend-sveltekit

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_FRONTEND_SVELTEKIT_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_SVELTEKIT_PROJECT_ID }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
