name: SvelteKit frontend checks

on:
  push:
    paths:
      - frontend-sveltekit/**
    branches:
      - main
  pull_request:
    paths:
      - frontend-sveltekit/**
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend-sveltekit

jobs:

  build:
    name: Install and build
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Svelte type check
      run: npm run check

    - name: Lint
      run: npm run lint
