name: Push Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-and-push:
    name: Build and push to GCP Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: waar-streamen-image
      PROJECT_ID: waar-streamen
      SA_NAME: github-actions
      REGISTRY_HOSTNAME: europe-west1-docker.pkg.dev
      REGISTRY_NAME: docker-images
    
    # From docs
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Authenticate GCP
      uses: google-github-actions/auth@v1
      with:
        service_account: ${{ env.SA_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:latest ./backend/

    - name: Configure Docker
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker ${{ env.REGISTRY_HOSTNAME }}

    - name: Generate reuseable variable for image
      run: |
        echo "IMAGE_LOCATION=${{ env.REGISTRY_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

    - name: Push docker container to GCP Artifact Registry
      env:
        # GIT_TAG: ${{ github.sha }}
        GIT_TAG: v0.1.0
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_LOCATION }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_LOCATION }}:${{ env.GIT_TAG }}
        docker push ${{ env.IMAGE_LOCATION }}:latest
        docker push ${{ env.IMAGE_LOCATION }}:${{ env.GIT_TAG }}