name: Push Docker image to GCP Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  permissions:
    contents: 'read'
    id-token: 'write'

  build-and-push:
    name: Build and push to GCP Container Registry
    runs-on: ubuntu-latest
    env:
      $IMAGE_NAME: waar-streamen
      $PROJECT_ID: waar-streamen
      $SA_NAME: github-actions
    
    steps:

    - uses: google-github-actions/auth@v1
      with:
        service_account: '${{ env.SA_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.GCP_SA_KEY }

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t $IMAGE_NAME:latest ./backend/Dockerfile

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Push docker container to GCP Container Registry
      env:
        # GIT_TAG: ${{ github.sha }}
        GIT_TAG: v0.1.0
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG